name: piSignage Server
version: "1.0.0"
slug: pisignage_server
description: Local Server to manage piSignage digital signage players
url: https://github.com/colloqi/pisignage-server
arch:
  - aarch64
  - amd64
  - armv7
init: false
ports:
  3000/tcp: 3000
ports_description:
  3000/tcp: Web interface
options:
  mongodb_uri: "mongodb://your-mongodb-host:27017/pisignage-dev"
  mongodb_timeout: 30
  node_env: "production"
schema:
  mongodb_uri: str
  mongodb_timeout: int(10,120)
  node_env: list(production|development)?
