name: "piSignage Server"
description: "Professional Digital Signage â€“ Full HA Add-on Port"
version: "3.0.0.1" 
slug: "pisignage_server"
url: "https://github.com/colloqi/pisignage-server"

arch:
  - aarch64

startup: services
boot: auto
init: false

ingress: true
ingress_port: 3000

panel_icon: "mdi:television-play"
panel_title: "piSignage"

map:
  - config:rw
  - share:rw
  - media:rw

ports:
  3000/tcp: 3000

watchdog: http://[HOST]:3000/api/status

schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  mongo_db_path: str
  media_storage: list(share|local)
  node_env: list(production|development)
  enable_healthcheck: bool
  restart_on_fail: bool

options:
  log_level: info
  mongo_db_path: /data/db
  media_storage: share
  node_env: production
  enable_healthcheck: true
  restart_on_fail: true
