name: "piSignage Server"
description: "Open source Digital Signage server. PORT TO HASSOS BY matsob0123."
version: "1.0.0"
slug: "pisignage_server"
arch:
  - aarch64
  - amd64
init: false
map:
  - config:rw
options:
  mongo_url: "mongodb://localhost:27017/pisignage-server"
schema:
  mongo_url: str
ports:
  8000/tcp: 8000